version: "3.1"
services:
  webserver:
    build: ./drupal
    image: gdacunda/drupal
    ports:
      - 8888:80
    volumes:
      - /var/www/html/modules
      - /var/www/html/profiles
      - /var/www/html/themes
      - /var/www/html/sites
    container_name: web
    restart: always

  database:
    build: ./postgres
    image: gdacunda/postgres
    ports:
      - 5432:5432
    container_name: db
    environment:
      POSTGRES_PASSWORD: example
    restart: always
    volumes:
      - 'postgres_data:/var/lib/postgresql/data'

volumes:
  postgres_data:
    driver: local
