version: 2
jobs:
  build:
    docker:
      - image: docker:18.06.3-ce-git
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache \
              py-pip=18.1-r0 curl
            pip install \
              docker-compose==1.23.2 \
              awscli==1.16.116
            curl -L -s https://releases.hashicorp.com/terraform/0.11.11/terraform_0.11.11_linux_amd64.zip -o /usr/local/bin/terraform.zip && unzip /usr/local/bin/terraform.zip -d /usr/local/bin && chmod +x /usr/local/bin/terraform
      - run:
          name: "Show info"
          command: |
            docker-compose --version
            docker version
            terraform --version
      - run:
          name: "Build images"
          command: docker-compose build
      - run:
          name: Push Docker images
          command: |
             docker login -u $DOCKER_USER -p $DOCKER_PASS
             docker tag ${CIRCLE_PROJECT_REPONAME}/drupal ${DOCKER_USER}/drupal:latest
             docker tag ${CIRCLE_PROJECT_REPONAME}/drupal ${DOCKER_USER}/drupal:1.0.$CIRCLE_BUILD_NUM
             docker push ${DOCKER_USER}/drupal:latest
             docker push ${DOCKER_USER}/drupal:1.0.$CIRCLE_BUILD_NUM
             docker tag ${CIRCLE_PROJECT_REPONAME}/postgres ${DOCKER_USER}/postgres:latest
             docker tag ${CIRCLE_PROJECT_REPONAME}/postgres ${DOCKER_USER}/postgres:1.0.$CIRCLE_BUILD_NUM
             docker push ${DOCKER_USER}/drupal:latest
             docker push ${DOCKER_USER}/drupal:1.0.$CIRCLE_BUILD_NUM
      - run:
          name: "Plan"
          command: |
             cd deployment
             if [ -e .terraform/modules ]; then rm -rf .terraform/modules; fi;
             terraform init -backend-config=backend.tfvars
             terraform state pull           
