version: 2
jobs:
  build:
    docker:
      - image: docker:18.06.3-ce-git
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache \
              py-pip=18.1-r0 curl
            pip install \
              docker-compose==1.23.2 \
              awscli==1.16.116
            curl -L -s https://releases.hashicorp.com/terraform/0.11.11/terraform_0.11.11_linux_amd64.zip -o /usr/local/bin/terraform.zip && unzip /usr/local/bin/terraform.zip -d /usr/local/bin && chmod +x /usr/local/bin/terraform
      - run:
          name: "Show info"
          command: |
            docker-compose --version
            docker version
            terraform --version
      - run:
          name: "Build image"
          command: docker-compose -p ${CIRCLE_PROJECT_REPONAME} build
      - run:
          name: "Push image"
          command: |
             docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
             docker tag ${CIRCLE_PROJECT_REPONAME}_webserver ${DOCKER_USER}/drupal:latest
             docker tag ${CIRCLE_PROJECT_REPONAME}_webserver ${DOCKER_USER}/drupal:1.0.$CIRCLE_BUILD_NUM
             docker push ${DOCKER_USER}/drupal:latest
             docker push ${DOCKER_USER}/drupal:1.0.$CIRCLE_BUILD_NUM
      - run:
          name: "Init terraform"
          command: |
             echo ${SSH_PUBLIC_KEY} > deployment/networking/keys/admin_ssh_key.pub
             cd deployment
             if [ -e .terraform/modules ]; then rm -rf .terraform/modules; fi;
             terraform init -backend-config=backend.tfvars
             terraform state pull           
      - run:
          name: "Plan terraform"
          command: |
             cd deployment
             terraform plan \
                -input=false \
                -var "webserver_image_tag=1.0.$CIRCLE_BUILD_NUM" \
                -var "webserver_cert_arn=$WEBSERVER_IAM_CERT" \
                -out tfplan
      - run:
          name: "Apply terraform"
          command: |
             cd deployment
             terraform apply -input=false -auto-approve tfplan

